#!/bin/sh
#!/bin/sh

sudo dnf install clang docker docker-compose keepassxc mpv lxappearance mpd ncmpcpp mpc bat lsd htop jetbrains-mono-fonts dunst torbrowser-launcher dejavu-sans-fonts google-noto-kufi-arabic-fonts google-noto-naskh-arabic-fonts pcmanfm xorg-x11-drv-amdgpu keepassxc docker docker-compose nitrogen neovim ibX11-xcb libxcb xinit fira-code-fonts pavucontrol xorg-x11-server-Xorg libX11-devel libXft-devel libXinerama-devel 

